### ISSUE TITLE
[prototype] How to disable the "basic auth" feature?

### ISSUE THREAD

**Issue by Noschvie** [shantanoo-desai/tiguitto#32]
How have the Traefik configuration files be changed to disable the "basic auth" feature for the Traefik dashboard ?
Thanks!

**Comment by shantanoo-desai** [comment]
@Noschvie ~~Can you elaborate a bit more. I do not understand exactly what you mean.~~

~~I think  in `traefik/traefik.toml`~~

~~dashboard = true~~
~~
~~Is where you can enable/disable the dashboard for traefik~~

## Edit

Have a look at this configuration in `configurations/middleware-http.toml`

```toml

        [http.middlewares.user-auth]
            [http.middlewares.user-auth.basicAuth]
                # Username:Password -> admin:tiguitto
                users = ["admin:$apr1$r3puowjd$lXRESWyaLtTa8Qdt6yD.0."]
```

Just comment or remove it out and you can see the dashboard without basic authentication

**Comment by shantanoo-desai** [comment]
@Noschvie Any update on this?

**Comment by Noschvie** [comment]
results in:
`192.168.1.101 - - [19/Feb/2021:06:58:21 +0000] "GET /dashboard HTTP/1.1" 404 19 "-" "-" 4 "api-router@file" "-" 0ms`

**Comment by shantanoo-desai** [comment]
There is a file `traefik/configuration/routers-http.toml`

Remove the middleware from the `routers-http.toml` file
```toml
        [http.routers.api-router]
            rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
            entryPoints = ["web"]
            middlewares = ["user-auth"] # YOU NEED TO DISABLE THIS!
            service = "api@internal"
```
